name = "comparator"
description = "Compare if two types have the same constructor in Gleam"
version = "1.0.1"
licences = ["Apache-2.0"]
repository = { type = "github", user = "dinkelspiel", repo = "comparator" }

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
